### ISSUE TITLE
Using <rxjs-spy> with SystemJS loader

### ISSUE THREAD

**Issue by mlc-mlapis** [cartant/rxjs-spy#10]
I tried to use `rxjs-spy` with Angular app 5.1.0 which is using SystemJS 0.20.19 loader but with no luck. It seams that this lib is very prommising so I would like to go much more deeply. But just for the simple imports ...
```
import { create } from 'rxjs-spy/spy-factory';
const spy = create();
import { tag } from 'rxjs-spy/operators/tag';
```

I tried these ways to config relevant part is `systemjs.config.js`:

**1) Standard way ... loading each JS file separately ...**
```
paths: {'npm:': './node_modules/'},
map: {
	...
	'rxjs-spy': 'npm:rxjs-spy',
},
packages: {
	...
	'rxjs-spy': {
		defaultExtension: 'js'
	}
}
``` 
... all files loaded successfully **except `plugin.js`**:
`Fetch finished loading: GET "http://localhost:8080/node_modules/rxjs-spy/spy-factory.js".`
`Fetch finished loading: GET "http://localhost:8080/node_modules/rxjs-spy/spy-core.js".`
...
`Fetch finished loading: GET "http://localhost:8080/node_modules/rxjs-spy/operators/hide.js".`
... **`Unexpected token < Evaluating http://localhost:8080/node_modules/rxjs-spy/plugin.js`**

**2) Re-bundling the lib ... loading all things in one step = preferred way ... using ...**
```
bundles: {
	"assets/rxjs-spy-bundle/RxSpy.min.js": [
		"rxjs-spy/*",
		"rxjs-spy/add/operator/*",
		"rxjs-spy/devtools/*",
		"rxjs-spy/operator/*",
		"rxjs-spy/operators/*",
		"rxjs-spy/plugin/*"
	]
}
```
and re-bundling via Gulp script:
```
gulp.task('rxjs-spy', function() {
	// SystemJS build options
	var options = {
		normalize: true,
		runtime: false,
		sourceMaps: false,
		sourceMapContents: false,
		minify: true,
		mangle: true
	};
	var builder = new systemjsbuilder('./');
	builder.config({
		paths: {
			"n:*": "node_modules/*",
			"rxjs-spy/*": "node_modules/rxjs-spy/*.js",
		},
		map: {
			"rxjs-spy": "n:rxjs-spy",
		},
		packages: {
			"rxjs-spy": {main: "index.js", defaultExtension: "js"},
		}
	});
	builder.bundle('rxjs-spy', 'assets/rxjs-spy-bundle/RxSpy.min.js', options);
});
```
... but the Gulp script ended with an error ...
**`unhandled rejection Error on fetch for rxjs-spy/plugin at file:///C:/Data/Projects/LocalHost/MLC-CSS/node_modules/rxjs-spy/plugin.js`**

**3) Using the UMD lib directly and loaded via `<script>` tag in `index.html` ...**
It does'n work at all ...
`<script src="node_modules/rxjs-spy/bundles/rxjs-spy.min.umd.js" type="text/javascript"></script>`
... an error appears:
**`Error: Unexpected token < Evaluating http://localhost:8080/rxjs-spy/spy-factory`**

**Summary**
It looks that there is something wrong with `plugin.js` because if not .... ways per 1) and 2) would work probably.

**Comment by cartant** [comment]
I don't know much about SystemJS. I've only ever used it when preparing Plunkr repros for AngularFire2 issues.

Numbers 1 and 2 appear to have the same problem: there is no `plugin.js` file. `plugin` is a directory and imports like this resolve to the index module in the `plugin` directory:

```ts
import {
    DebugPlugin,
    Deck,
    DevToolsPlugin,
    GraphPlugin,
    LetPlugin,
    LogPlugin,
    Notification,
    PausePlugin,
    Plugin,
    SnapshotPlugin,
    StackTracePlugin,
    StatsPlugin,
    SubscriptionSnapshot
} from "./plugin";
```

This is a fairly idiomatic way of writing imports and if SystemJS has a problem with it, there should be a general solution to it. Many libraries perform imports like this. For example, most of [these imports](https://github.com/angular/angular/blob/5.1.0/packages/core/src/core.ts#L14-L38) all refer to directories.

Regarding 3, something seems amiss with the error. If you are using the pre-built bundle, why is the URL referring to `http://localhost:8080/rxjs-spy/spy-factory`?

**Comment by cartant** [comment]
Have a look at [this comment](https://github.com/systemjs/systemjs/issues/1433#issuecomment-267262289).

**Comment by mlc-mlapis** [comment]
@cartant ... thanks for your ideas ... this https://github.com/systemjs/systemjs/issues/1433#issuecomment-267262289 leads to to error `Unexpected token < Evaluating http://localhost:8080/node_modules/rxjs-spy/index.js/spy-factory` ... it is a request that is related to `import { create } from 'rxjs-spy/spy-factory';` which is transpiled to `var spy_factory_1 = require("rxjs-spy/spy-factory");`.

**Comment by mlc-mlapis** [comment]
@cartant ... I will try to create `plugin.js` first to solve 1) and 2) ... it should be the simplest way I think. I let you know the result ...

**Comment by mlc-mlapis** [comment]
@cartant ... I did the test with `plugin.js` placed directly to the directory `rxjs-spy` which contains:
```
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./plugin/debug-plugin"));
__export(require("./plugin/devtools-plugin"));
__export(require("./plugin/graph-plugin"));
__export(require("./plugin/let-plugin"));
__export(require("./plugin/log-plugin"));
__export(require("./plugin/pause-plugin"));
__export(require("./plugin/plugin"));
__export(require("./plugin/snapshot-plugin"));
__export(require("./plugin/stack-trace-plugin"));
__export(require("./plugin/stats-plugin"));
```
and I repeated steps 1) and 2) ... and now the problem dis-appeared and I was able to re-bundle `rxjs-spy` using SystemJS Builder with Gulp script to the single bundle `RxSpy.min.js`:
```
gulp.task('rxjs-spy', function() {
	var options = {
		normalize: true,
		runtime: false,
		sourceMaps: false,
		sourceMapContents: false,
		minify: true,
		mangle: true
	};
	var builder = new systemjsbuilder('./');
	builder.config({
		paths: {
			"n:*": "node_modules/*",
			"circular-json/*": "node_modules/circular-json/*.js",
			"stacktrace-js/*": "node_modules/stacktrace-js/*.js",
			"error-stack-parser/*": "node_modules/error-stack-parser/*.js",
			"stack-generator/*": "node_modules/stack-generator/*.js",
			"stacktrace-gps/*": "node_modules/stacktrace-gps/*.js",
			"stackframe/*": "node_modules/stackframe/*.js",
			"source-map/*": "node_modules/source-map/*.js",
			"rxjs/*": "node_modules/rxjs/*.js",
			"rxjs-spy/*": "node_modules/rxjs-spy/*.js"
		},
		map: {
			"circular-json": "n:circular-json",
			"stacktrace-js": "n:stacktrace-js",
			"error-stack-parser": "n:error-stack-parser",
			"stack-generator": "n:stack-generator",
			"stacktrace-gps": "n:stacktrace-gps",
			"stackframe": "n:stackframe",
			"source-map": "n:source-map",
			"rxjs": "n:rxjs",
			"rxjs-spy": "n:rxjs-spy"
		},
		packages: {
			"circular-json": {main: "build/circular-json.js", defaultExtension: "js"},
			"stacktrace-js": {main: "stacktrace.js", defaultExtension: "js"},
			"error-stack-parser": {main: "error-stack-parser.js", defaultExtension: "js"},
			"stack-generator": {main: "stack-generator.js", defaultExtension: "js"},
			"stacktrace-gps": {main: "stacktrace-gps.js", defaultExtension: "js"},
			"stackframe": {main: "stackframe.js", defaultExtension: "js"},
			"source-map": {main: "source-map.js", defaultExtension: "js"},
			"rxjs": {main: "Rx.js", defaultExtension: "js"},
			"rxjs-spy": {main: "index.js", defaultExtension: "js"}
		}
	});
	builder.bundle('rxjs-spy', 'assets/rxjs-spy-bundle/RxSpy.min.js', options);
});
```
Everything works now and there is just one warning in the run-time:
**`RxSpy.min.js: Value passed as error notification is not an Error instance = NoMatch {segmentGroup: UrlSegmentGroup}`** which comes from following lines ... it comes probably from Angular because of the name **`welcome`** which the the primary route of this demo app.
![image](https://user-images.githubusercontent.com/5693835/33912973-3797b790-df98-11e7-9f0f-a7729ac31734.png)

```
var postSelectObserver = {
    complete: function() {
        notify_(function(plugin) {
            return plugin.beforeComplete(ref);
        }, function() {
            return subscriber.complete();
        }, function(plugin) {
            return plugin.afterComplete(ref);
        });
    },
    error: function(error) {
        if (!(error instanceof Error)) {
            **console.warn("Value passed as error notification is not an Error instance =", error);**
        }
        notify_(function(plugin) {
            return plugin.beforeError(ref, error);
        }, function() {
            return subscriber.error(error);
        }, function(plugin) {
            return plugin.afterError(ref, error);
        });
    },
    next: function(value) {
        notify_(function(plugin) {
            return plugin.beforeNext(ref, value);
        }, function() {
            return subscriber.next(value);
        }, function(plugin) {
            return plugin.afterNext(ref, value);
        });
    },
    unsubscribed: false
};
```

**Comment by cartant** [comment]
If that's the amount of work that you have to do to consume a library, I think you should get SystemJS to consume the bundle. From memory, that's what the SystemJS configuration I was using in the Plunkrs was doing. As I mentioned above, your error with the bundle that mentioned `http://localhost:8080/rxjs-spy/spy-factory` suggests that something else was happening.

Regarding the warning, `rxjs-spy` will warn if non-`Error` instances are passed to `error` notifications, as I consider that to be bad practice - i.e. using `error` notifications for control flow. If the errors are not coming from your code, you can safely ignore them.

**Comment by cartant** [comment]
If you look into the distributed bundle and find problems, let me know and I'll re-open this. Otherwise, you appear to have things working - albeit in a somewhat fragile way (if I change `rxjs-spy`'s dependencies, your build will break).

**Comment by mlc-mlapis** [comment]
@cartant ... yes, I know ... but it'll be easy to recognize and adjust the build config.

**Comment by mlc-mlapis** [comment]
@cartant ... in reality the same thing ...re-bundling ... is necessary to do with RxJS lib itself if you want to use it as a single bundle with Angular and SystemJS loader.

**Comment by cartant** [comment]
Yeah. I just really don't like SystemJS. That's all. Just my opinion, though.

However, I'm curious as to what your reason is for not using the Angular CLI. I wasn't a fan of its early versions, but I've come around to it and now I rather like it.

**Comment by mlc-mlapis** [comment]
@cartant ... SystemJS is not as bad as it looks on the first moment. It allows JIT (any update is under 1 sec from a developer point of view) and also AOT mode (without bundling under 3 secs, with complete bundling under 5 secs) to develop and run Angular apps.

So it give us:
* working alternative build system for JIT + AOT,
* fast development cycles for our development team,
* a possibility to run multiple Angular apps without including repeated libs in them and use a browser cache instead (for Angular libs, RxJS, ...) to switch apps,
* and we are working on early stages of ABC concept to be able to do the same in future with even more advantages.

**Comment by cartant** [comment]
Hmm, I'm not convinced; SystemJS has caused me so much hassle in the past and it's the **fourth** :grimacing: bundling tool (after Browserify, Webpack, and Rollup) that I've had to deal with.

But it sounds like it's working for you, so that's cool.

**Comment by mlb6** [comment]
I just got the same warning with Angular Universal : 
> Value passed as error notification is not an Error instance = NoMatch 
The first request to the server is giving a 504 Bad Gateway. Other requests are fine. 

It is probably due to the fact that on sever-side the tsconfig is configured to use commonjs module.
In order remove the Bad Gateway issue I had to remove rxjs-spy. And now it works fine.

You could probably re-open this issue in order to make it compatible with angular universal.

**Comment by cartant** [comment]
@mlb6 Unless you are using System JS - and it doesn't sound like you are - yours is a separate issue, so please open it as such.

And the message you referenced is a warning that can be ignored - as explained above.
