### ISSUE TITLE
ERROR TypeError: rxjs_1.of is not a function in an Electron Angular 5 application

### ISSUE THREAD

**Issue by Eshva** [cartant/rxjs-spy#25]
Namaste!
I try to use your tool in an Electron Angular 5 application. I try to create the spy in the bootstrap file like this:

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { ApplicationModule } from 'modules/application/application.module';
import { environment } from 'environments';
import { create } from 'rxjs-spy';

if (environment.production) {
	enableProdMode();
}

create();

platformBrowserDynamic().bootstrapModule(ApplicationModule);
```

And I have this error in the console:

```
ERROR TypeError: rxjs_1.of is not a function
    at StackTracePlugin.beforeSubscribe (stack-trace-plugin.js:63)
    at spy-core.js:426
    at Array.forEach (<anonymous>)
    at notify_ (spy-core.js:304)
    at Observable.SpyCore.coreSubscribe_ [as subscribe] (spy-core.js:426)
    at subscribeToResult (subscribeToResult.js:67)
    at MergeMapSubscriber._innerSub (mergeMap.js:138)
    at MergeMapSubscriber._tryNext (mergeMap.js:135)
    at MergeMapSubscriber._next (mergeMap.js:118)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:92)
```

Seams like the problem happens when your tool registers plugins for Chromium Dev Tools.
What I do wrong? Can it be used in an Electron application at all?

**Comment by Eshva** [comment]
I've found how to do that!

1. Seams like StackTracePlugin broken or doesn't work in Electron. So we should exclude it. ```create``` function has parameter to disable default plugins. After that I can plug necessary plugins using ```plug``` function.

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { ApplicationModule } from 'modules/application/application.module';
import { environment } from 'environments';
import { tag } from 'rxjs-spy/operators/tag';
import { of } from 'rxjs/observable/of';
import { create } from 'rxjs-spy';
import { SnapshotPlugin, GraphPlugin } from 'rxjs-spy/plugin';

if (environment.production) {
	enableProdMode();
}

const spy = create({ defaultPlugins: false });
spy.plug(
	new GraphPlugin(),
	new SnapshotPlugin(spy));
of(1, 2, 3).pipe(tag('qqq')).subscribe();

platformBrowserDynamic().bootstrapModule(ApplicationModule);
```

2. Order of plugins matters! If I put SnapshotPlugin in the first place and GraphPlugin after that it will spam in the console with 'Graphing is not enabled.' It's a bad pattern when order matters.

P.S. I used in this case rxjs-spy@6.1.0. I need to check the latest 7 version.

**Comment by Eshva** [comment]
I've tested rxjs-spy@7.0.1 with my Angular 5.2.1 application.
1. It doesn't work. It has no error on create but when I try to call rxSpy.show() in the console it throws the same error.
2. If the order of plugins SnapshotPlugin and then GraphPlugin it spams 3 warnings 'Graphing is not enabled.'. Seams like the exact number of values in the observable.

**Comment by cartant** [comment]
Version 7 has an RxJS version 6 peer, so you should have seen an npm/yarn warning when installing it. It will now work with RxJS version 5.

And regarding your initial comment, `rxjs_1.of is not a function` seems something more fundamental than something related to the DevTools. What versions of RxJS and rxjs-spy do you have installed?

**Comment by cartant** [comment]
I've released new versions of 6 and 7 that log config-related warnings to the console only once.

However, I'm not convinced that your issue is related to Electron. Your error is related to the `of` observable factory and it's used in only two places in `stack-trace-plugin.ts`: [here](https://github.com/cartant/rxjs-spy/blob/v6.1.1/source/plugin/stack-trace-plugin.js#L29) and [here](https://github.com/cartant/rxjs-spy/blob/v6.1.1/source/plugin/stack-trace-plugin.js#L79). You will need to investigate why such a basic method cannot be required.

Configuring the DevTools plugin should have no effect in environments in which the DevTools are unavailable, so including it in the default configuration should not be a problem. Any attempt at communication with the DevTools is within a [guard](https://github.com/cartant/rxjs-spy/blob/v7.0.2/source/plugin/devtools-plugin.ts#L94).

**Comment by Eshva** [comment]
I need to check it further at home tonight. It can be related only to inappropriate version of rxjs-spy and rxjs itself. To do that I need to check it with complete cleaning of node_modules directory.
But anyway, please state it clearly in the readme.md that rxjs-spy@6 is for rxjs@5 and rxjs-spy@7 is for rxjs@6. In my case I don't watch for warnings in the console when I do install npm packages because I have many other warnings related to platform specific dependencies (fs for instance). Like this:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-linux@1.8.6 (node_modules\app-builder-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-linux@1.8.6: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.6 (node_modules\app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.8.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
Many other people do the same I think.

**Comment by cartant** [comment]
It's in the [CHANGELOG](https://github.com/cartant/rxjs-spy/blob/master/CHANGELOG.md#700-2018-04-25) and the [peer dependency in the `package.json`](https://github.com/cartant/rxjs-spy/blob/v7.0.2/package.json#L57-L59) clearly states that it requires RxJS `^6.0.0` and will effect an appropriate warning. Writing it down someplace else and hoping that devs will reads the docs - even if they choose to ignore installation warnings - is wishful thinking IMO.

**Comment by Eshva** [comment]
Ok, I've tested it and seams like it was my fault. I don't need to select some plugins and can use the default plugin set. Please close this issue as a wrong one.
