### ISSUE TITLE
Unable to install on Node v10.x

### ISSUE THREAD

**Issue by srounce** [cartant/rxjs-spy#31]
Installing on Node v10 and I get the following error:
```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
```

**Comment by cartant** [comment]
`upath` is a dependency of `karma`:

```
$ npm list upath
rxjs-spy@7.0.2 C:\Users\Nicholas\git\github\rxjs-spy
`-- karma@2.0.4
  `-- chokidar@2.0.4
    `-- upath@1.1.0
```

I've updated the lock file and the `package.json` for `upath` now contains:

```
  "engines": {
    "node": ">=4"
  },
```

Closing this, but let me know if you have further problems after fetching the latest commits from this repo.
