### ISSUE TITLE
Devtool Tab?

### ISSUE THREAD

**Issue by joeljeske** [cartant/rxjs-spy#33]
Have you had any interest in a devtools tab? Are you aware of any forks or plugins, similar to a Redux dev tool tab, or VueX dev tool tabs? 

Thanks! Great project, by the way!

**Comment by joeljeske** [comment]
Oh! I missed that it was related. My bad. 

Do you plan on picking that back up? Would you ever be interested in help?

**Comment by cartant** [comment]
Sure. Always interested in having others help. Sorting out the messed-up directory structure in the `panel` project and upgrading it to the latest Angular is something that I should get done soon. After that's done, it should be easier to work with.

**Comment by joeljeske** [comment]
Ok sounds good. Yea I would likely be interested in adding functionality. Do you have any goals or plans written for what it could be at v1?

**Comment by joeljeske** [comment]
Closing. Project = https://github.com/cartant/rxjs-spy-devtools

**Comment by cartant** [comment]
Yeah, I have a bunch of ideas and notes in a private issue tracker. However, I would not say that they are sufficiently coherent to form a plan.

Once I've cleaned up the project, etc. I'll look at organising them so they can be discussed.

Right now, I'll create a GitHub issue for the clean up and upgrade, etc. in the other repo. If you want to subscribe to that issue, you'll be notified of when it's done and then we can take it from there.

**Comment by cartant** [comment]
https://github.com/cartant/rxjs-spy-devtools/issues/1
