### ISSUE TITLE
console warning: spy-core.js:339 rxSpy is deprecated; use spy instead

### ISSUE THREAD

**Issue by wardbell** [cartant/rxjs-spy#40]
Worrying console message that appears one time.

Trying this promising library for the first time with `angular@^6.1.9` and `rxjs@^6.3.3`

**Comment by cartant** [comment]
That warning is shown the first time the `rxSpy` global is used in the console. I got sick of typing the upper-case S and renamed it. I can see how the message can be confusing/worrying. I'll re-word it. Thanks for pointing it out.

**Comment by cartant** [comment]
Closed by https://github.com/cartant/rxjs-spy/commit/b6f2a10c987df4f740a31db75e9886866ff42ab4
