### ISSUE TITLE
Hangs IE11

### ISSUE THREAD

**Issue by steveschmitt** [cartant/rxjs-spy#42]
In an Angular 6.1.9 app, we added the following to `app.module.ts`:
```
import { create as rxjsCreate } from 'rxjs-spy';
rxjsCreate(); // Start rxjs-spy
```
We find `rxjs-spy` works great in all other browsers, but in IE11, the browser hangs when attempting to load the app.  The screen is blank and IE shows an error message at the bottom:
```
localhost is not responding due to a long-running script
```
If I wait for about 10 minutes, the app will finally show up.  But then each navigation within the app takes 1-2 minutes to complete and even popping up a modal takes 10 seconds.  These should be near-instantaneous.

If I comment out the `rxjsCreate()` call, the app runs normally.

Yes, I know IE11 is slow.  But what is `rxjs-spy` doing that slows things down so drastically?

**Comment by cartant** [comment]
> But what is `rxjs-spy` doing that slows things down so drastically?

I don't know. I don't use or support IE.

However, you might find something useful/actionable in comments in this issue: https://github.com/cartant/rxjs-spy/issues/6
