### ISSUE TITLE
ng add rxjs-spy

### ISSUE THREAD

**Issue by nsklyarov** [cartant/rxjs-spy#46]
Please, add "ng add" support;
Now if i try in ng-generated project:
```
ng add rxjs-spy
```
i catch this error:
```
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

this issue implicitly relates to this issue:

https://github.com/cartant/rxjs-spy/issues/39

**Comment by cartant** [comment]
I've not used Angular for some time. It's not clear to me what `ng add` is supposed to mean in the context of an arbitrary, non-Angular-specific package - which is what this is.

In any case, ATM, I don't have the time to add Angular-specific features - such as schematic support.
