### ISSUE TITLE
rxjs-spy-devtools status

### ISSUE THREAD

**Issue by xiaoxiangmoe** [cartant/rxjs-spy#51]
What is the status of rxjs-spy-devtools? 
What usage was it originally intended to provide? 
Is there any plan to continue development?

**Comment by cartant** [comment]
If you are referring to the `rxjs-spy-devtools` repo, that was archived some time ago and development was moved elsewhere - to a private repo. `rxjs-spy-devtools` was little more than an experiment.

Regarding the tools, see [this Twitter thread](https://twitter.com/aaronfrost/status/1226961213562728451)
