### ISSUE TITLE
Auto tagging

### ISSUE THREAD

**Issue by ewhauser** [cartant/rxjs-spy#53]
I'm starting to explore `rxjs-spy` for use in a large Angular application. We have about ~1000 components so there's a large number of observables. Prior to discovering `rxjs-spy`, I was exploring using a Typescript compiler plugin to automatically generate debugging information for each subscription (i.e. name, location, and code of each subscription) and then using that information for leak detection in my tests.

I was thinking about pivoting this code to use `rxjs-spy` under the covers instead. Is there any downside to automatically adding `tag(...)` to every subscription? It's relatively straightforward to do in a compiler plugin - the toughest part seems like coming up with a usable name.

Thanks!

**Comment by cartant** [comment]
The [RxJS Tools](https://rxjs.tools/) that I'm working on do something similar - but not using `tag` - and a whole lot more. All of my tool-related development is happening there; I don't imagine I will be doing any further work on `rxjs-spy`.

**Comment by joshribakoff** [comment]
I subscribed. I'd love to help with it / try it out @cartant
