### ISSUE TITLE
Feature Request: Add esm support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [cartant/rxjs-spy#55]
Add esm output and module mainField.

I'm using Angular 10 and see warning:

```
WARNING in my-lib depends on 'rxjs-spy/operators'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by cartant** [comment]
This won't happen anytime soon. Maybe never. This package has three dependencies that do not themselves have ESM support:

```
"circular-json": "^0.5.0",
"error-stack-parser": "^2.0.1",
"stacktrace-gps": "^3.0.2"
```

So, AFAICT, there is little point in adding ESM support - which would otherwise be relatively straightforward - to this this package.

**Comment by xiaoxiangmoe** [comment]
It seems that vite and snowpack users are inconvenient to use this library. 😭

**Comment by cartant** [comment]
Anyone wanting/needing ESM will have to use a tool like https://github.com/getify/moduloze - that's what I'd have to use for the dependencies listed above, but I have other priorities.

**Comment by cartant** [comment]
Actually, I can probably fix this using Rollup. I might look at it on the weekend.

**Comment by cartant** [comment]
7.5.3 should include Rollup-generated, flattened ESM bundles.
